### ISSUE TITLE
Conflicting requirements

### ISSUE THREAD

**Issue by santanahugo** [Farzad-R/LLM-Zero-to-Hundred#1]
Hello! I was unable to install the requirements. I tried both via requirements.txt and the manual installation process as instructed in WebRAGQuery. Using the latter method, I'm getting the following error:

ERROR: Cannot install chainlit==0.7.700 and duckduckgo-search==3.9.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    chainlit 0.7.700 depends on httpx<0.25.0 and >=0.23.0
    duckduckgo-search 3.9.6 depends on httpx>=0.25.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Are there updated versions of these packages in your environment?

Thanks

**Comment by Farzad-R** [comment]
Hello! I double-checked the libraries and the versions were the same as the ones on my previous environment. But anyway I created a new environment and tested the project with the newer versions of the libraries. I added a new requirements.txt explicitly for WebRagQuery. If you want to install manually, the key libraries are:

chainlit==0.7.700 duckduckgo-search==4.1.1 openai==0.28.0 chromadb==0.4.22 fake-useragent==1.4.0 pydantic==2.5.1 langchain==0.0.354 bs4==0.0.1 tiktoken==0.5.2 pandas==2.1.4

As you suggested, for most of the libraries there is no need for a specific version. I just kept them for clarity as some of them are changing drastically. The most important libraries are pydantic==2.5.1 and openai==0.28.0 as I know their latest versions do not work with the current code. For the rest, you are flexible to use their most recent version. Please create a fresh environment and check with the new libraries. Also please note that I am using Python 3.11.5 on a Windows 11 OS with Anaconda. 

Hope it solved the issue. Let me know if something else came up.
