### ISSUE TITLE
:~/LLM-Zero-to-Hundred/WebRAGQuery$ (from versions: none) ERROR: No matching distribution found for bzip2==1.0.8

### ISSUE THREAD

**Issue by DrivenIdeaLab** [Farzad-R/LLM-Zero-to-Hundred#11]
for :~/LLM-Zero-to-Hundred/WebRAGQuery$

Cant get past bzip2--1.0.8

**Comment by Farzad-R** [comment]
Hello,
I am not sure which OS you are using but the requirements.txt files were initially prepared for Windows. But I just updated the requirements.txt files in WebRAGQuery and WebGPT projects and only included the necessary libraries. This should help you execute the project regardless of the OS. Please let me know if this solves the issue
