### ISSUE TITLE
PIP install fails

### ISSUE THREAD

**Issue by gordingin** [Farzad-R/LLM-Zero-to-Hundred#19]
Hi, when I follow the pip install -r requirements.txt file, it ends up failing with the following..

Downloading simple_websocket-1.1.0-py3-none-any.whl (13 kB)
Using cached zipp-3.20.2-py3-none-any.whl (9.2 kB)
Using cached protobuf-4.25.5-cp37-abi3-macosx_10_9_universal2.whl (394 kB)
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: tiktoken, literalai, syncer
  Building wheel for tiktoken (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tiktoken (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/registry.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/__init__.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/core.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/model.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/load.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      copying tiktoken/_educational.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      creating build/lib.macosx-11.1-arm64-cpython-312/tiktoken_ext
      copying tiktoken_ext/openai_public.py -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken_ext
      running egg_info
      writing tiktoken.egg-info/PKG-INFO
      writing dependency_links to tiktoken.egg-info/dependency_links.txt
      writing requirements to tiktoken.egg-info/requires.txt
      writing top-level names to tiktoken.egg-info/top_level.txt
      reading manifest file 'tiktoken.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'Makefile'
      adding license file 'LICENSE'
      writing manifest file 'tiktoken.egg-info/SOURCES.txt'
      copying tiktoken/py.typed -> build/lib.macosx-11.1-arm64-cpython-312/tiktoken
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiktoken
  Building wheel for literalai (setup.py) ... done

**Comment by gordingin** [comment]
I created my conda environment with python 3.12 instead of 3.11. 
After I deleted my env and recreated it with 3.11, the pip install worked.

**Comment by Farzad-R** [comment]
Glad to hear it. I used python 3.11 for all my projects in my GitHub so far. In case I switch to 3.12, I'd mention it in my readme file.
