### ISSUE TITLE
Add  Multimodal ChatBot, PEFT: Parameter-Efficient Finetuning, LLM Pretraining

### ISSUE THREAD

**Issue by aditya-AI** [Farzad-R/LLM-Zero-to-Hundred#6]
Hi @Farzad-R  thanks for this amazing repository, can you please also add the remaining three modules?

**Comment by Farzad-R** [comment]
Hi aditya-AI,
Thanks for the kind words. None of these projects were ready in the first place and I am developing them one at a time. The list just comes from my initial plan. The multimodal chatbot is 99% ready. I just need to make some small changes and I will upload it in the repository and also on YouTube by the end of this week. That project was huge. It took me around 3 weeks to finish it. after that, I will be adding a project about RAG with knowledge graph. And after that, I probably would work on PEFT and LLM pertaining. So, keep an eye on the repository and by the end of the week an amazing chatbot will be added to it. It is the best and the biggest open-source chatbot that I have developed so far.
