### ISSUE TITLE
=haa95532_0 and =pypi_0 preventing pip install -r requirements.txt from installing 

### ISSUE THREAD

**Issue by DrivenIdeaLab** [Farzad-R/LLM-Zero-to-Hundred#9]
Ubuntu wsl
Windows 11

If you remove the =haa95532_0 and =pypi_0 preventing pip install -r requirements.txt from installing you will get a successful install 

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
aiofiles=23.2.1=pypi_0
aiohttp=3.9.1=pypi_0
aiosignal=1.3.1=pypi_0
altair=5.2.0=pypi_0
annotated-types=0.6.0=pypi_0
anyio=3.7.1=pypi_0
asgiref=3.7.2=pypi_0
asyncer=0.0.2=pypi_0
attrs=23.2.0=pypi_0
backoff=2.2.1=pypi_0
bcrypt=4.1.2=pypi_0
beautifulsoup4=4.12.2=pypi_0
bidict=0.22.1=pypi_0
bs4=0.0.1=pypi_0
build=1.0.3=pypi_0
bzip2=1.0.8=he774522_0
ca-certificates=2023.12.12=haa95532_0
cachetools=5.3.2=pypi_0
certifi=2023.11.17=pypi_0
cffi=1.16.0=pypi_0
chainlit=0.7.700=pypi_0
charset-normalizer=3.3.2=pypi_0
chroma-hnswlib=0.7.3=pypi_0
chromadb=0.4.22=pypi_0
click=8.1.7=pypi_0
colorama=0.4.6=pypi_0
coloredlogs=15.0.1=pypi_0
contourpy=1.2.0=pypi_0
curl-cffi=0.5.10=pypi_0
cycler=0.12.1=pypi_0
dataclasses-json=0.5.14=pypi_0
deprecated=1.2.14=pypi_0
duckduckgo-search=4.1.1=pypi_0
fastapi=0.100.1=pypi_0
fastapi-socketio=0.0.10=pypi_0
ffmpy=0.3.1=pypi_0
filelock=3.13.1=pypi_0
filetype=1.2.0=pypi_0
flatbuffers=23.5.26=pypi_0
fonttools=4.47.0=pypi_0
frozenlist=1.4.1=pypi_0
fsspec=2023.12.2=pypi_0
google-auth=2.26.1=pypi_0
googleapis-common-protos=1.62.0=pypi_0
gradio=4.13.0=pypi_0
gradio-client=0.8.0=pypi_0
greenlet=3.0.3=pypi_0
grpcio=1.60.0=pypi_0
h11=0.14.0=pypi_0
httpcore=0.17.3=pypi_0
httptools=0.6.1=pypi_0
httpx=0.24.1=pypi_0
huggingface-hub=0.20.2=pypi_0
humanfriendly=10.0=pypi_0
idna=3.6=pypi_0
importlib-metadata=6.11.0=pypi_0
importlib-resources=6.1.1=pypi_0
jinja2=3.1.2=pypi_0
jsonpatch=1.33=pypi_0
jsonpointer=2.4=pypi_0
jsonschema=4.20.0=pypi_0
jsonschema-specifications=2023.12.1=pypi_0
kiwisolver=1.4.5=pypi_0
kubernetes=28.1.0=pypi_0
langchain=0.0.354=pypi_0
langchain-community=0.0.8=pypi_0
langchain-core=0.1.6=pypi_0
langsmith=0.0.77=pypi_0
lazify=0.4.0=pypi_0
libffi=3.4.4=hd77b12b_0
lxml=5.0.0=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=2.1.3=pypi_0
marshmallow=3.20.1=pypi_0
matplotlib=3.8.2=pypi_0
mdurl=0.1.2=pypi_0
mmh3=4.0.1=pypi_0
monotonic=1.6=pypi_0
mpmath=1.3.0=pypi_0
multidict=6.0.4=pypi_0
mypy-extensions=1.0.0=pypi_0
nest-asyncio=1.5.8=pypi_0
numpy=1.26.3=pypi_0
oauthlib=3.2.2=pypi_0
onnxruntime=1.16.3=pypi_0
openai=0.28.0=pypi_0
openssl=3.0.12=h2bbff1b_0
opentelemetry-api=1.22.0=pypi_0
opentelemetry-exporter-otlp=1.22.0=pypi_0
opentelemetry-exporter-otlp-proto-common=1.22.0=pypi_0
opentelemetry-exporter-otlp-proto-grpc=1.22.0=pypi_0
opentelemetry-exporter-otlp-proto-http=1.22.0=pypi_0
opentelemetry-instrumentation=0.43b0=pypi_0
opentelemetry-instrumentation-asgi=0.43b0=pypi_0
opentelemetry-instrumentation-fastapi=0.43b0=pypi_0
opentelemetry-proto=1.22.0=pypi_0
opentelemetry-sdk=1.22.0=pypi_0
opentelemetry-semantic-conventions=0.43b0=pypi_0
opentelemetry-util-http=0.43b0=pypi_0
orjson=3.9.10=pypi_0
overrides=7.4.0=pypi_0
packaging=23.2=pypi_0
pandas=2.1.4=pypi_0
pillow=10.2.0=pypi_0
pip=23.3.1=py311haa95532_0
posthog=3.1.0=pypi_0
protobuf=4.25.1=pypi_0
pulsar-client=3.4.0=pypi_0
pyasn1=0.5.1=pypi_0
pyasn1-modules=0.3.0=pypi_0
pycparser=2.21=pypi_0
pydantic=2.5.1=pypi_0
pydantic-core=2.14.3=pypi_0
pydub=0.25.1=pypi_0
pygments=2.17.2=pypi_0
pyjwt=2.8.0=pypi_0
pyparsing=3.1.1=pypi_0
pypdf=3.17.4=pypi_0
pypika=0.48.9=pypi_0
pyproject-hooks=1.0.0=pypi_0
pyprojroot=0.3.0=pypi_0
pyreadline3=3.4.1=pypi_0
python=3.11.5=he1021f5_0
python-dateutil=2.8.2=pypi_0
python-dotenv=1.0.0=pypi_0
python-engineio=4.8.1=pypi_0
python-graphql-client=0.4.3=pypi_0
python-multipart=0.0.6=pypi_0
python-socketio=5.10.0=pypi_0
pytz=2023.3.post1=pypi_0
pyyaml=6.0.1=pypi_0
referencing=0.32.0=pypi_0
regex=2023.12.25=pypi_0
requests=2.31.0=pypi_0
requests-oauthlib=1.3.1=pypi_0
rich=13.7.0=pypi_0
rpds-py=0.16.2=pypi_0
rsa=4.9=pypi_0
semantic-version=2.10.0=pypi_0
setuptools=68.2.2=py311haa95532_0
shellingham=1.5.4=pypi_0
simple-websocket=1.0.0=pypi_0
six=1.16.0=pypi_0
sniffio=1.3.0=pypi_0
soupsieve=2.5=pypi_0
sqlalchemy=2.0.25=pypi_0
sqlite=3.41.2=h2bbff1b_0
starlette=0.27.0=pypi_0
sympy=1.12=pypi_0
syncer=2.0.3=pypi_0
tenacity=8.2.3=pypi_0
tiktoken=0.5.2=pypi_0
tk=8.6.12=h2bbff1b_0
tokenizers=0.15.0=pypi_0
tomli=2.0.1=pypi_0
tomlkit=0.12.0=pypi_0
toolz=0.12.0=pypi_0
tqdm=4.66.1=pypi_0
typer=0.9.0=pypi_0
typing-extensions=4.9.0=pypi_0
typing-inspect=0.9.0=pypi_0
tzdata=2023.4=pypi_0
uptrace=1.22.0=pypi_0
urllib3=1.26.18=pypi_0
uvicorn=0.23.2=pypi_0
vc=14.2=h21ff451_1
vs2015_runtime=14.27.29016=h5e58377_2
watchfiles=0.20.0=pypi_0
websocket-client=1.7.0=pypi_0
websockets=11.0.3=pypi_0
wheel=0.41.2=py311haa95532_0
wrapt=1.16.0=pypi_0
wsproto=1.2.0=pypi_0
xz=5.4.5=h8cc25b3_0
yarl=1.9.4=pypi_0
zipp=3.17.0=pypi_0
zlib=1.2.13=h8cc25b3_0

**Comment by Farzad-R** [comment]
Hello,
I updated the requirements.txt files in WebRAGQuery and WebGPT projects and only included the necessary libraries. This should help you execute the project regardless of the OS. Please let me know if this solves the issue.
